application: cdn1024mb
version: 1
runtime: python27 
api_version: 1
threadsafe: true

handlers:
- url: /css
  static_dir: stylesheet

- url: /imagenes
  static_dir: imagenes

- url: /files
  static_dir: files

- url: /js
  static_dir: javascripts

- url: /.*
  static_files: index.html
  upload: index.html